#ifndef ECC_CRYPTO
#define ECC_CRYPTO



typedef struct eccPoint
{
	mpz_t x;
	mpz_t y;

	unsigned char pointAtInf;
} eccPoint;


typedef struct eccParams
{
	mpz_t p;			// F_p modulo factor
	mpz_t a;			// coeff of x^1 in curve
	mpz_t b;			// constant coeff in curve
	struct eccPoint *g;	// Generator of subgroup  (is a point, an element of group)
	mpz_t n;			// Order of subgroup generated by g.
} eccParams;


typedef struct ecc_Ciphertext
{
	struct eccPoint *sessionKey;
	struct eccPoint *msgPart;
} ecc_Ciphertext;


typedef struct u_v_Pair_ECC
{
	struct eccPoint *u;
	struct eccPoint *v;
} u_v_Pair_ECC;


typedef struct ECC_PK
{
	struct eccPoint *g;
	struct eccPoint *g_x;
	struct eccPoint *h;
	struct eccPoint *h_x;
} ECC_PK;




#include "eccUtils.c"
#include "eccGroup.c"
#include "ecc_enc.c"




#endif