typedef struct eccPoint
{
	mpz_t x;
	mpz_t y;

	unsigned char pointAtInf;
} eccPoint;


typedef struct eccParams
{
	mpz_t p;			// F_p modulo factor
	mpz_t a;			// coeff of x^1 in curve
	mpz_t b;			// constant coeff in curve
	struct eccPoint *g;	// Generator of subgroup  (is a point, an element of group)
	mpz_t n;			// Order of subgroup generated by g.
} eccParams;


typedef struct eccPubKey
{

}eccPubKey;



#include "eccUtils.c"
#include "ecc_enc.c"