#ifndef ECC_CRYPTO_HOM
#define ECC_CRYPTO_HOM



typedef struct eccPoint_Hom
{
	mpz_t x;
	mpz_t y;
	mpz_t z;

	unsigned char pointAtInf;
} eccPoint_Hom;


typedef struct eccParams_Hom
{
	mpz_t p;				// F_p modulo factor
	mpz_t a;				// coeff of x^1 in curve
	mpz_t b;				// constant coeff in curve
	struct eccPoint_Hom *g;	// Generator of subgroup  (is a point, an element of group)
	mpz_t n;				// Order of subgroup generated by g.
} eccParams_Hom;


typedef struct ecc_Ciphertext_Hom
{
	struct eccPoint_Hom *sessionKey;
	struct eccPoint_Hom *msgPart;
} ecc_Ciphertext_Hom;


typedef struct u_v_Pair_ECC_Hom
{
	struct eccPoint_Hom *u;
	struct eccPoint_Hom *v;
} u_v_Pair_ECC_Hom;


typedef struct ECC_PK_Hom
{
	struct eccPoint_Hom *g;
	struct eccPoint_Hom *g_x;
	struct eccPoint_Hom *h;
	struct eccPoint_Hom *h_x;
} ECC_PK_Hom;








#include "eccUtils_Hom.c"
#include "eccGroup_Hom.c"
#include "ecc_enc_Hom.c"




#endif